### ISSUE TITLE
Can't get stdout data from logstash

### ISSUE THREAD

**Issue by jamiebuxxx** [jsirex/simple-logstash-cookbook#13]
Hello, 

When we were using the older version of this cookbook that was using the `runit`, we were able to get see the stdout logs from `/var/log/logstash-service/run`. With the new systemd init service, we can see logstash error logs at `/opt/logstash/logs/logstash-plain.log`. But when enabling `stdout { codec => rubydebug }` from the logstash config, we don't see any output to the logstash log location or syslog. I know if I start logstash from the CLI, logs will show up on screen. Just curious if its possible to get logs redirection using the systemd or another logstash method.

**Comment by jsirex** [comment]
Did you try `journalctl` to inspect the logs? Also option `--quiet` may suppress logs.
Let me know if this won't help.

**Comment by jamiebuxxx** [comment]
Ah, I literally just looked at `journalctl` for the unit and get see the stdout messages. I'm able to see the logs using the following command. 

```
journalctl -x -u logstash-service --no-pager
```

Maybe this is something we can add to the README under the logstash-service area. Thanks for the help!
