### ISSUE TITLE
Support path.data for logstash_service

### ISSUE THREAD

**Issue by dsharkou** [jsirex/simple-logstash-cookbook#14]
Thanks for your cookbook!

I have multiple instances of logstash on ubuntu and it fired exceptions on start second, etc. services that the first service is started and lock path.data folder. So I should change path.data for the second, etc. ones. Can you please add property to logstash_args something like this:
`args << "--path.data #{logstash_path_data}" if logstash_path_data`
or/and common:
`args << "#{logstash_custom_argument}" if logstash_custom_argument`
as additional arguments.

I think it should be common solution rather 

Thanks in advance!

**Comment by jsirex** [comment]
I've released cookbook v1.0.0. It automatically deals with data  (creates `/var/lib/<name>/data` folder)
custom_args properties was added.

I need some time to test it. I hope it resolves your issue.

PS. I dropped logstash 1.x support by default. But it is still possible to override logstash args.

**Comment by dsharkou** [comment]
Thanks!
