### ISSUE TITLE
filters not being applied in latest cookbook version 

### ISSUE THREAD

**Issue by jamiebuxxx** [jsirex/simple-logstash-cookbook#15]
Hello, 

I recently updated to the latest version of the this cookbook and my filter stopped working. I'm using the default systemd service. I noticed that instead of using the `-f` flag when starting logstash, its using `--path.config /etc/logstash-service_name/conf.d`. Based on the read I configured the logstash configs to go under the /etc/logstash-service_name/conf.d:

```
~# ls -la /etc/logstash-broker/conf.d/
total 24
drwxr-xr-x 2 logstash logstash 4096 Apr 23 18:30 .
drwxr-xr-x 3 root     root     4096 Apr 23 18:30 ..
-rw-r----- 1 logstash logstash  614 Apr 23 18:30 20_norm_filebeat.conf
-rw-r----- 1 logstash logstash  103 Apr 23 18:30 20_norm_rsyslog.conf
-rw-r----- 1 logstash logstash 2039 Apr 23 18:30 21_norm_location.conf
-rw-r----- 1 logstash logstash  986 Apr 23 18:30 logstash-broker.conf
```
The standard config `logstash-broker.config` works fine, but the additional configs are being applied. Since this was breaking our environment, I rolled back to v0.6.3 of this cookbook. But I would like to understand the difference between the recent changes and why config.d configs are no longer working.

**Comment by jsirex** [comment]
I had to rework this cookbook because since logstash 1.x there were a lot changes, additional yml config, pipelines, pluging, etc. That way I moved configs in `conf.d` directory, like in original distributive.

If you're using logstash 1.x it is still possible, but requires additional configuration. Consider https://github.com/jsirex/simple-logstash-cookbook/blob/master/libraries/logstash_service_base.rb for available config options.

From official manual:

> -f, --path.config CONFIG_PATH
> Load the Logstash config from a specific file or directory. If a directory is given, all files in that directory will be concatenated in lexicographical order and then parsed as a single config file. Specifying this flag multiple times is not supported. If you specify this flag multiple times, Logstash uses the last occurrence (for example, -f foo -f bar is the same as -f bar).
> 
> You can specify wildcards (globs) and any matched files will be loaded in the order described above. For example, you can use the wildcard feature to load specific files by name:
> 
> bin/logstash --debug -f '/tmp/{one,two,three}'
> With this command, Logstash concatenates three config files, /tmp/one, /tmp/two, and /tmp/three, and parses them into a single config.

So I think that it must work as expected. I also did few tests. 

There is example of usage: https://github.com/jsirex/simple-logstash-cookbook/blob/master/test/fixtures/cookbooks/simple-logstash-test/recipes/default.rb
There are two services defined: `logstash` and `logstash-two`. 
And in https://github.com/jsirex/simple-logstash-cookbook/blob/master/test/integration/default/default_spec.rb test is expecting two services and two different folders for each service. All files under `conf.d` passed to logstash daemon.

Could you please provide me additional information, what is expected and what is incorrect? 
Also could you share some code and/or logstash version, os version?

**Comment by jamiebuxxx** [comment]
We're running Logstash v5.2.2 on Ubuntu 16.04. We have been running this setup for over a 6months+ now. I did look at the test suite and our test past as well. So it not an issue of errors. I only noticed this when looking up logs and I didn't see any filters being applied. 

One of the difference in our setup versus the example test suite is that we have both the input and output in one config:
```
input {
  kafka {
    bootstrap_servers => "kafka_endpoint:9092"
    topics => ["logstash-broker"]
    codec => json
  }
}

output{
  tcp {
    host => "graylog_host"
    port => 5555
    codec => json_lines
  }
  #stdout { codec => rubydebug }
}

```
 and the filter separated into individual configs. As shown in the `ls` command above.

I would expect the config ordering with `--path.config` to behave the same way as `-f`, but that doesn't seem to be case. After reverting back to the previous cookbook version, everything is working fine. 

So the test it to create an logstash config with both an input and output and then include additional filter configs. Seen some test data and make sure the filters are being applied correct. In the meantime, I will try to use the `custom_args` with the `-f` set to see that makes a difference. I will also look to see if the `path.config` and `-f` flag behave differently.

**Comment by jamiebuxxx** [comment]
Ah!! There is a difference. 
```
path.config |
The path to the Logstash config for the main pipeline. If you specify a directory or wildcard, config files are read from the directory in alphabetical order.
```
When the `-f` flag "concatenated in lexicographical order and then parsed as a single config file."

So in my case, I will need to change my recipes put my files in a custom directory and use `-f custom_dir` in the `custom_args` resource for the logstash_service

**Comment by jsirex** [comment]
Thank you for this info. I see that behavior of this flag between `1.x` and `>=2.x` is different. 

If you want change flag to `-f` I have "backup plan":
you can set flag for config by property:

```ruby
logstash_service 'logstash' do
  config_path_flag '-f'
  ...
end
```

I also updated documentation.

Currently, I'm not sure should I change default behavior or not, or refactor cookbook somehow...

**Comment by jamiebuxxx** [comment]
Sounds good! I will do some testing with `config_path_flag` property. 

As for the default behavior, that is a good question. Personally, I like the `-f` flag because I can create different configs and have Logstash sort them out. I think it boils down to your use case. But its awesome that there's an ability to use the either method. That's the important bit!

**Comment by jamiebuxxx** [comment]
The `config_path_flag` property under the` logstash-service` resource worked great! I think we can close this issue for now. Thanks for your help!
