### ISSUE TITLE
The default recipe creates a group using the user value

### ISSUE THREAD

**Issue by yogin** [jsirex/simple-logstash-cookbook#2]
Looking at the `default` recipe, when creating the system group for logstash it uses the `user` value instead of the `group`:

``` ruby
roup 'logstash group' do
  group_name node['logstash']['user']
  action :create
  system true
end
```

Should be:

``` ruby
roup 'logstash group' do
  group_name node['logstash']['group']
  action :create
  system true
end
```

And I just want to say thank you for this cookbook, I tried a bunch of others and they were so complicated to use, this one has helped me a lot to get started!

**Comment by jsirex** [comment]
Fix in 0.2.2
