### ISSUE TITLE
Cookbook compilation error

### ISSUE THREAD

**Issue by ckoparkar** [jsirex/simple-logstash-cookbook#3]
Hi, I'm getting a error using this cookbook. My setup is;
- metadata.rb 
  
  `depends 'simple-logstash'
  depends 'runit'`
- Berksfile
  
  `cookbook 'simple-logstash', '~> 0.2.2'
  cookbook 'runit', '~> 1.7.2'`
- recipes/logstash.rb
  
  `include_recipe 'java::default'
  include_recipe 'simple-logstash'`

If I dont include 'runit', I get this error,

`ERROR: Cookbook runit not found. If you're loading runit from another cookbook, make sure you configure the dependency in your metadata`

After I included it, kitchen converge fails saying,

```
Recipe Compile Error in /tmp/kitchen/cookbooks/simple-logstash/libraries/provider_logstash_service.rb
NameError
       ---------
       uninitialized constant Chef::Provider::Service::Runit

       Cookbook Trace:
       ---------------
         /tmp/kitchen/cookbooks/simple-logstash/libraries/provider_logstash_service.rb:4:in `<class:Service>'
         /tmp/kitchen/cookbooks/simple-logstash/libraries/provider_logstash_service.rb:3:in `<class:Provider>'
         /tmp/kitchen/cookbooks/simple-logstash/libraries/provider_logstash_service.rb:2:in `<class:Chef>'
         /tmp/kitchen/cookbooks/simple-logstash/libraries/provider_logstash_service.rb:1:in `<top (required)>'
```

I'm new to Chef so this may not be a problem with this cookbook but with my configuration. Any ideas on how to resolve this ?

**Comment by jsirex** [comment]
Do you use a wrapper cookbook to call this one?
Which version of Chef you used?

**Comment by ckoparkar** [comment]
Yeah, the wrapper is supposed to install logstash and configure it with some templates.
`Chef Development Kit Version: 0.6.2`

**Comment by jsirex** [comment]
My cookbook depends on runit, but in minor version (1.7.2) they break some functionality: renamed namespace for provider `RunitService`.

Try to use runit cookbook version 1.5.18 till I close this issue

**Comment by ckoparkar** [comment]
Sure, thanks :smiley:
