### ISSUE TITLE
Some examples of use would be really helpful...

### ISSUE THREAD

**Issue by trekr5** [jsirex/simple-logstash-cookbook#4]
Hi,

I've started to use the simple-logstash cookbook for the simple of logstash.

How do you use the cookbook to turn logstash off and on like a service? what is the correct syntax?
I've tried:-

logstash_service "logstash" do
 action :enable, :start
end

and it hasn't worked.

How would I specify the location of my configuration file, opt/logstash-1.5.3/conf.d/logstash.conf, in a simple-logstash cookbook resource as well?

Many thanks

**Comment by jsirex** [comment]
Hi,

Take a look at test cookbook for logstash. This is typical usage:
https://github.com/jsirex/simple-logstash-cookbook/tree/master/test/fixtures/cookbooks/simple-logstash-test

**Comment by jsirex** [comment]
Also, fixed url in readme. Thanks.

Please, let me know if this example will help you

**Comment by trekr5** [comment]
Hi,

I've copied over my config file(sample.conf) to etc/logstash/sample.conf and started up my logstash with logstash_service 'logstash' in my recipe and it isn't using the config file.

This is my recipe:-

```
cookbook_file "sample.conf" do 
path "/etc/logstash/sample.conf"
p "sample.conf copied into /etc/logstash/sample.conf..."
end

 logstash_service 'logstash' do
  logstash_config_path node['logstash']['prefix_conf']  
 action [:enable, :start]
 end    
```

attributes:

```
   default['logstash']['prefix_conf'] = '/etc/logstash'
```

and this is sample.conf:-

```
input {
    file {
      path => "/tmp/access_log"
      start_position => "beginning"
    }
}


output {
 file 
   {
    path => "/tmp/output_log"
    codec => rubydebug
   }
}
```

and also finally if I wanted to add plugins, where would I define my plugin path? For example I would like to upload output from logstash into an AWS S3 bucket. Looking at the logstash installed by your cookbook, it appears that in /opt/logstash-1.5.3/lib/pluginmanager/, there exists a PluginManager module. Would I copy my s3 plugin to the /opt/logstash-1.5.3/lib/pluginmanager directory and then ?... Please let me know how I can use this.

Many thanks!

**Comment by jsirex** [comment]
You can check what you actually get looking at file `/etc/sv/logstash/run`.
You don'y have to change `prefix_conf` path. Service uses `/etc/<service_name>` folder as default:

``` ruby
...
logstash_service 'logstash' # this is enough
```

And looks like your example also should work.
If you want to specify plugin path use `logstash_plugin_path`: https://github.com/jsirex/simple-logstash-cookbook/blame/master/README.md#L73

**Comment by jsirex** [comment]
Do you still have any issues or I can close this?
