### ISSUE TITLE
Chef run enters infinite loop

### ISSUE THREAD

**Issue by ihulsbus** [jsirex/simple-logstash-cookbook#8]
Hi.

I am using your community cookbook to install Logstash 5.1, but I'm encountering something that places the chef run into a loop. 

This is a snippet just for the infinite loop starts: https://gist.github.com/ih16/c369307341ffa3ed62d9ea4c34a3eb8a

And this is the snippet when the run enters the infinite loop: 
https://gist.github.com/ih16/e2fb56292fd45b0714b051341fe2d6c6

I have the folowing recipe: 

```
include_recipe 'java::default'
include_recipe 'simple-logstash::default'

logstash_service 'logstash' do
  action :create
end
```

with the following attributes:
```
default['java']['install_flavor'] = 'oracle'
default['java']['oracle']['accept_oracle_download_terms'] = true
default['java']['jdk_version'] = '8'
default['logstash']['download_url'] = 'https://artifacts.elastic.co/downloads/logstash/logstash-5.1.2.tar.gz'
default['logstash']['version'] = '5.1.2'
default['logstash']['checksum'] = 'ffa4e370c6834f8e2591a23147a74a8cea04509efc6cf8c02b5cc563455c559c'
```

As soon as I cancel the run when the loop starts, and restart it, everything goes fine. 

Any idea's what could trigger this behaviour?

**Comment by jsirex** [comment]
Could you please specify chef version, os?
Do you have only this recipe in run list or any other recipes?

**Comment by ihulsbus** [comment]
OS is Ubuntu Server 16.04 LTS, chef version is 12.5. 
The node has the following roles with corresponding cookbooks in it's run list:

```
Base: 
  - apt, version 5.1.0
  - ntp, version 3.2.0
  - timezone_lwrp, version 0.1.10
  - chef-client, version 3.1.0
  - unattended-upgrades, version 0.1.2
Logstash
  - logstash_server, version 0.1.0
```

**Comment by jsirex** [comment]
I tried to reproduce this issue locally without success.
It works as expected. BTW I think "warn: cloning resource" is suspicious for me.

**Comment by ihulsbus** [comment]
I suspected that this was a problem that is specific to our environment. We deploy a ubuntu 16.04.2 LTS Qcow image on Openstack via Terraform. Terraform also triggers the chef run. Maybe that that causes an issue. I've created a different cookbook to install logstash in the mean time. So this issue may be closed if desired.

Cheers
