### ISSUE TITLE
Logstash 5.3 support

### ISSUE THREAD

**Issue by jamiebuxxx** [jsirex/simple-logstash-cookbook#9]
I've been using the cookbook for a long time now and its been working great. I noticed that whenwe tried to update Logstash to the latest version in this cookbook, Logstash would not start because some of the long command line flag names have changed.

https://www.elastic.co/guide/en/logstash/5.2/running-logstash-command-line.html

**Comment by jsirex** [comment]
This is also related to #7 
Anyway, we need move forward. Probably, I have to upgrade cookbook to support latest logstash version and drop legacy code.

**Comment by jsirex** [comment]
Released 0.5.1
